### ISSUE TITLE
Scaffold command silently fails in an already initialized directory

### ISSUE THREAD

**Issue by alwaysAn0n** [bigearth/bitbox-cli#10]
bitbox-cli version: 0.7.2
operating system: 64bit Debian Linux (Jessie)
npm version: 5.5.1
node version: v9.0.0

With a globally installed version of bitbox-cli, running the command `bitbox scaffold --framework angular` from within a directory that has already been initialized via `npm init` produces the output below but doesn't actually make any changes to the filesystem.

```
Scaffolding angular app in current directory
All done. ✅
```

**Comment by cgcardona** [comment]
The `scaffold` flag is now nested as a flag under the `bitbox new` command.

W/ the new flow a user would no longer run `bitbox scaffold` but instead will run `bitbox new myApp --scaffold angular` so this bug should no longer be an issue.
