### ISSUE TITLE
Is it possible build-in the mainnet connection?

### ISSUE THREAD

**Issue by cyio** [bigearth/bitbox-cli#15]
like this https://github.com/bitpay/bitcore-lib/blob/cash/lib/networks.js#L194

**Comment by cgcardona** [comment]
Yes, when you create an instance of the `TransactionBuilder` class you can pass in a `"bitcoincash"` argument to get the mainnet or pass in a `"testnet"` argument to get testnet.

```
let transactionBuilder = new BITBOX.TransactionBuilder('bitcoincash');
```
[More info on `TransactionBuilder`](https://www.bitbox.earth/bitboxcli/transactionbuilder)

Is that what you mean?

**Comment by cgcardona** [comment]
I think this has been resolved. Closing.
