### ISSUE TITLE
RawTransactions example methods fail

### ISSUE THREAD

**Issue by Gamaroff** [bigearth/bitbox-cli#18]
I am running the Node scaffold app without problems.

I'm using a Bitcoin ABC server in Testnet.

The following two example methods from the Docs fail with this message 
**"TypeError: Cannot read property 'message' of undefined"**
```
BITBOX.RawTransactions.createRawTransaction([{"txid":"myid","vout":0}], {"address":0.01})
  .then((result) => {
    console.log(result);
  }, (err) => { console.log(err);
  });
```
and

```
BITBOX.RawTransactions.decodeRawTransaction('01000000013ba3edfd7a7b12b27ac72c3e67768f617fc81bc3888a51323a9fb8aa4b1e5e4a000000006a4730440220540986d1c58d6e76f8f05501c520c38ce55393d0ed7ed3c3a82c69af04221232022058ea43ed6c05fec0eccce749a63332ed4525460105346f11108b9c26df93cd72012103083dfc5a0254613941ddc91af39ff90cd711cdcde03a87b144b883b524660c39ffffffff01807c814a000000001976a914d7e7c4e0b70eaa67ceff9d2823d1bbb9f6df9a5188ac00000000')
  .then((result) => {
    console.log(result);
  }, (err) => { console.log(err);
  });
```
All help is greatly appreciated and thanks for the great library.

**Comment by cgcardona** [comment]
Hi. A couple of things

First, how are you creating your instance of `BITBOXCli`? Are you passing in the credentials for your test node?

```
let BITBOXCli = require('bitbox-cli/lib/bitboxcli').default;
let BITBOX = new BITBOXCli({
  protocol: 'http',
  host: 'ip.address.of.node',
  port: 18332,
  username: '',
  password: ''
});
```

Confirm you are passing in the correct credentials there. We have a mainnet full node we run for people to test their code on. Feel free to use it.

```
    {
      protocol: "http",
      host: "138.68.54.100",
      port: "8332",
      username: "bitcoin",
      password: "xhFjluMJMyOXcYvF"
    }
```

Try using the [TransactionBuilder](https://www.bitbox.earth/bitboxcli/transactionbuilder) class for creating and signing transactions. `BITBOX.RawTransactions.createRawTransaction` is being removed in the next version. 

The following works:

```
BITBOX.RawTransactions.decodeRawTransaction('01000000013ba3edfd7a7b12b27ac72c3e67768f617fc81bc3888a51323a9fb8aa4b1e5e4a000000006a4730440220540986d1c58d6e76f8f05501c520c38ce55393d0ed7ed3c3a82c69af04221232022058ea43ed6c05fec0eccce749a63332ed4525460105346f11108b9c26df93cd72012103083dfc5a0254613941ddc91af39ff90cd711cdcde03a87b144b883b524660c39ffffffff01807c814a000000001976a914d7e7c4e0b70eaa67ceff9d2823d1bbb9f6df9a5188ac00000000')
  .then((result) => {
    console.log(result);
  }, (err) => { console.log(err);
  });
```
If you put it all on one line. 

```
BITBOX.RawTransactions.decodeRawTransaction('01000000013ba3edfd7a7b12b27ac72c3e67768f617fc81bc3888a51323a9fb8aa4b1e5e4a000000006a4730440220540986d1c58d6e76f8f05501c520c38ce55393d0ed7ed3c3a82c69af04221232022058ea43ed6c05fec0eccce749a63332ed4525460105346f11108b9c26df93cd72012103083dfc5a0254613941ddc91af39ff90cd711cdcde03a87b144b883b524660c39ffffffff01807c814a000000001976a914d7e7c4e0b70eaa67ceff9d2823d1bbb9f6df9a5188ac00000000').then((result) => { console.log(result); }, (err) => { console.log(err); });
```
I've updated the docs to all be on one line so this error doesn't happen again: https://www.bitbox.earth/bitboxcli/rawtransactions#decodeRawTransaction

We have a #bitbox chatroom on http://ambassador.cash. Please join us there for more in depth help.

**Comment by cgcardona** [comment]
Here are complete steps for doing transactions: https://bigearth.github.io/bitblog/2018/04/01/complete-transaction-setup.html

Please let me know if you still have troubles. I'll gladly help debug. Thanks.

**Comment by Gamaroff** [comment]
Hi Gabriel

Thank you for the comprehensive reply.
When using the credentials to your test node the code works great.

It must have something to do with how my ABC node is configured.
I can confirm that my node is running fine because bitcoin-cli works for all RPC calls.
I have configured the Bitbox config with the correct IP etc.

The Bitbox config 
```
const bitboxcli = require('bitbox-cli/lib/bitboxcli').default;

const BITBOX = new bitboxcli({
	protocol : 'http',
	host     : 'localhost',
	port     : 8332,
	username : '',
	password : '',
	corsproxy: false,
	test     : true
});
```
My ABC node is running in Testnet.

The bitcoin.conf looks like this
```
rpcuser=
rpcpassword=
server=1
pid=/var/run/bitcoin/bitcoin.pid
testnet=1
txindex=1
rpcallowip=10.0.0.0/16
```

I'm running the bitbox cli on the same machine as the node.

**Comment by cgcardona** [comment]
### Your BITBOX config

```js
const bitboxcli = require('bitbox-cli/lib/bitboxcli').default;

const BITBOX = new bitboxcli({
	protocol : 'http',
	host     : 'localhost',
	port     : 8332,
	username : '',
	password : '',
	corsproxy: false,
	test     : true
});
```

Update `port` to `18332`. `bitcoind`'s JSON PRC is port `8332` for mainnet and port `18332` for testnet.

### `test : true`

Also remove `test: true`. That's only used internally when you run `npm test`. We create an instance of `BITBOXCli` [w/ no config object](https://github.com/bigearth/bitbox-cli/blob/master/test/RawTransactions.js#L6) which [sets a default config object](https://github.com/bigearth/bitbox-cli/blob/master/src/bitboxcli.js#L26) w/ `test: true`.

Then [below that](https://github.com/bigearth/bitbox-cli/blob/master/src/bitboxcli.js#L38) if `test: true` we set `baseURL` to `/`. This is all ceremony for stubbing out HTTP requests w/ axios.

`bitbox-cli` has 1400+ passing tests w/ 80%+ coverage. High quality code is what we're all about.

### Remote testnet

I set up a full testnet node today. Feel free to use it

```
host: 167.99.110.201
port: 18332
user: bitcoin
pass: rD9yw2Y9RkOnYjYnDX
```

### Proxy services

We offer 2 proxy services for getting around CORS issues. If you run `bitbox proxy` we fire up a `localhost:1337` server. Then pass `corsproxy: 'local'` in to your code and all your `POST` requests will hit the local server before hitting the network.

Or you can pass `corsproxy: 'remote'` in to your code and it will `POST` to https://proxy.bitbox.earth which is a remote reverse proxy we host for people to use. It's rate limited at 50 requests per 3 minutes but of course I can white list your domain.

#### Hong Kong

Are you giving a presentation at the Coingeek conference in Hong Kong? I'll be there. Let's connect if you have time.

**Comment by Gamaroff** [comment]
Thank you! 
Silly port mistake. I corrected it and it works great.

I will be at Coingeek and would love to meet up with you. 
We are playing around with Bitbox and very keen on using it in Centbee.
