### ISSUE TITLE
Error when attempting to run `bitbox console`

### ISSUE THREAD

**Issue by oorion** [bigearth/bitbox-cli#7]
I'm running bitbox app but I get the following error when trying to run `bitbox console`:

Error: Cannot find module '/Users/orion/personal/bitbox-cli/bitbox.js'

**Comment by cgcardona** [comment]
Hello! When launching `bitbox console` BITBOX will look for a `bitbox.js` file in that directory. Inside your `bitbox.js` are credentials for connecting to a locally running BITBOX GUI or a remote full node.

Try this

```
cd ~/
bitbox new --title myApp
cd myApp/
```

This will create an empty BITBOX app structure w/ a `bitbox.js` file. If you open that `bitbox.js` file you'll see

```js
exports.config = {
  networks: {
    development: {
      protocol: "http",
      host: "localhost",
      port: "8332",
      username: "",
      password: ""
    }
  }
};
```
Those are credentials to send requests to a locally running BITBOX GUI. You can add credentials for a full node like so:

```js
exports.config = {
  networks: {
    development: {
      protocol: "http",
      host: "localhost",
      port: "8332",
      username: "",
      password: ""
    },
    production: {
      protocol: "http",
      host: "ip.of.full.node",
      port: "8332",
      username: "username",
      password: "password"
    }
  }
};
```

Then when you run `bitbox console --environment production` your console will send requests to the node w/ those credentials and IP address.

It's also possible to store common creds in a `.bitboxrc` file in your home directory.

Please let me know if that doesn't fix the issue. Also there is [a slack channel ](https://bitboxearth.slack.com) I can invite you to for more in depth help.

Thanks for checking out BITBOX. I'm super responsive so let me know any other questions. 🎩

**Comment by cgcardona** [comment]
Hi, just touching bases on this to see if it's been resolved on your end. Thanks

**Comment by cgcardona** [comment]
Closing.
